-- trigger 테스팅
-- emp01 생성 하고 트리거 생성한다(입력이 될때마다 입력값을 출력해주는 트리거를 만든다)

DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(20),
    JOB VARCHAR2(50)
);

DESC EMP01;

CREATE OR REPLACE TRIGGER EMP01_TRIGGER
    AFTER INSERT
    ON EMP01
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE(:NEW.EMPNO || ' , '||:NEW.ENAME||' , '||'신입사원이 입사했습니다.');
END;
/

INSERT INTO EMP01 VALUES((SELECT NVL(MAX(EMPNO),0)+1 FROM EMP01), DBMS_RANDOM.STRING('U',4), 'IT_DEV');

SELECT * FROM EMP01;

-- 사원 테이블에 새로운 데이터 즉 신입 사원이 들어오면 급여 테이블에 새로운 데이터를 자동으로 생성하고 싶을 경우, 사원 테이블에 트리거를 설정하여 구연할 수 있다.
CREATE TABLE SAL01(
    SALNO NUMBER(4),
    SAL NUMBER,
    EMPNO NUMBER(4)
    );

ALTER TABLE SAL01 ADD CONSTRAINTS SAL01_SALNO_PK PRIMARY KEY(SALNO);
ALTER TABLE SAL01 ADD CONSTRAINTS SAL01_EMPNO_FK FOREIGN KEY(EMPNO) REFERENCES EMP01(EMPNO);

CREATE SEQUENCE SAL01_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 100000
    NOCYCLE
    CACHE 2;

CREATE OR REPLACE TRIGGER EMP01_TRIGGER2
    AFTER INSERT
    ON EMP01
    FOR EACH ROW
    BEGIN
        INSERT INTO SAL01 VALUES(SAL01_SEQ.NEXTVAL, 100000, :NEW.EMPNO);
        DBMS_OUTPUT.PUT_LINE(:NEW.EMPNO ||'번의 사원이 SAL01에 잘 들어왔습니다');
    END;
/

INSERT INTO EMP01 VALUES((SELECT NVL(MAX(EMPNO),0)+1 FROM EMP01), DBMS_RANDOM.STRING('U',4), 'IT_DEV');
SELECT * FROM EMP01;
SELECT * FROM SAL01;

-- EMP01에서 사원의 정보를 제거 했을때 SAL01에 해당되는 사원의 정보가 삭제되도록 프로그램하시오
CREATE OR REPLACE TRIGGER EMP01_TRIGGER3
    AFTER DELETE
    ON EMP01
    FOR EACH ROW
    BEGIN
    -- SAL01 해당되는 사원의 정보가 삭제
    DELETE FROM SAL01 WHERE EMPNO = :OLD.EMPNO;
    DBMS_OUTPUT.PUT_LINE(:OLD.EMPNO ||'번호가 SAL01에서 삭제되었습니다');
    END;
/

DELETE FROM EMP01 WHERE EMPNO = 3;
SELECT * FROM EMP01;
SELECT * FROM SAL01;

-- 입고 테이블에 상품이 입력되면 입고 수량을 상품 테이블의 재고 수량에 추가하는 트리거 작성해 보자.

-- PRODUCT 테이블 작성
CREATE TABLE PRODUCT(
    PCODE CHAR(6),
    PNAME VARCHAR(12) NOT NULL,
    PCOMPANY VARCHAR(12),
    PPRICE NUMBER(8),
    STOCK NUMBER DEFAULT 0,
    CONSTRAINT PRODUCT_PCODE_PK PRIMARY KEY(PCODE)
);

-- RECEIVING 테이블 작성
CREATE TABLE RECEIVING(
    RNO NUMBER(6),
    PCODE CHAR(6),
    PDATE DATE DEFAULT SYSDATE,
    RQTY NUMBER(6),
    RPRICE NUMBER(8),
    RAMOUNT NUMBER(8),
    CONSTRAINT RECEIVING_RNO_PK PRIMARY KEY(RNO),
    CONSTRAINT RECIEVING_PCODE_FK FOREIGN KEY(PCODE) REFERENCES PRODUCT(PCODE)
);

-- PRODUCT 테이블 샘플 데이터 입력
INSERT INTO PRODUCT(PCODE, PNAME, PCOMPANY, PPRICE) VALUES('A00001','세탁기', 'LG', 1500000); 

INSERT INTO PRODUCT(PCODE, PNAME, PCOMPANY, PPRICE) VALUES('A00002','컴퓨터', 'LG', 1000000); 

INSERT INTO PRODUCT(PCODE, PNAME, PCOMPANY, PPRICE) VALUES('A00003','냉장고', '삼성', 4500000); 
SELECT * FROM PRODUCT;

-- RECEIVING 테이블에 상품이 입력되면 PRODUCT 수량을 상품 테이블의 재고 수량에 추가하는 트리거 작성
CREATE OR REPLACE TRIGGER TRG_IN
    AFTER INSERT
    ON RECEIVING
    FOR EACH ROW
    BEGIN
        UPDATE PRODUCT
            SET STOCK = STOCK + :NEW.RQTY
            WHERE PCODE = :NEW.PCODE;
    END;
/

-- 트리거 테스트
INSERT INTO RECEIVING(RNO, PCODE, RQTY, RPRICE, RAMOUNT) VALUES(SAL01_SEQ.NEXTVAL, 'A00001', 5, 850000, 950000);

SELECT * FROM PRODUCT;
SELECT * FROM RECEIVING;

-- 갱신 트리거 만들고 입고 수량 변경하기
CREATE OR REPLACE TRIGGER TRG_UP
    AFTER UPDATE
    ON RECEIVING
    FOR EACH ROW
    BEGIN
        UPDATE PRODUCT
        SET STOCK = STOCK + (-:OLD.RQTY +:NEW.RQTY)
        WHERE PCODE = :NEW.PCODE;
    END;
/

UPDATE RECEIVING SET RQTY = 10 WHERE RNO = 4;

SELECT * FROM PRODUCT;
SELECT * FROM RECEIVING;

-- 삭제 트리거 만들고 RECEIVING 테이블에 상품이 삭제되면 PRODUCT에서 삭제 수량을 빼준다
CREATE OR REPLACE TRIGGER TRG_DEL
    AFTER DELETE
    ON RECEIVING
    FOR EACH ROW
    BEGIN
        UPDATE PRODUCT SET STOCK = STOCK -(:OLD.RQTY) WHERE PCODE = :OLD.PCODE;
    END;
/

DELETE FROM RECEIVING WHERE RNO = 3;

SELECT * FROM PRODUCT;
SELECT * FROM RECEIVING;

-- function 부서 번호를 입력하면 부서명을 리턴 해주는 함수를 만드시오
-- 부서번호가 없는 번호라면 '해당부서없음' 값으로 리턴 하시오
CREATE OR REPLACE FUNCTION GET_DEPARTMENT_NAME_FUNC(VDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE)
RETURN VARCHAR2
    IS
        VDEPARTMENT_NAME VARCHAR2(100);
        VCOUNT NUMBER :=0;
    BEGIN
        -- 해당 부서의 카운트를 체크
        SELECT COUNT(*) INTO VCOUNT FROM EMPLOYEES WHERE DEPARTMENT_ID = VDEPARTMENT_ID;
        IF VCOUNT = 0
            THEN VDEPARTMENT_NAME := '해당부서없음';
        ELSE
            SELECT DEPARTMENT_NAME INTO VDEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = VDEPARTMENT_ID;
        END IF;
        
        RETURN VDEPARTMENT_NAME;
    END;
/

-- 함수를 이용해서 부서번호를 매개변수 등록하고 부서명 구하는 기능 사용
SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, GET_DEPARTMENT_NAME_FUNC(DEPARTMENT_ID)
    AS "DEPARTMENT_NAME"
    FROM EMPLOYEES
    WHERE FIRST_NAME = 'Steven';

VARIABLE VNAME VARCHAR2;
EXECUTE :VNAME := GET_DEPARTMENT_NAME_FUNC(90);
PRINT VNAME;
