-- 순위함수 RANK(), DENSE_RANK(), ROWNUM
DROP TABLE EMP02;
CREATE TABLE EMP02
AS
SELECT * FROM EMPLOYEES WHERE 1=1;

SELECT * FROM EMP02;

-- ROWNUM 구하는 순위(공동순위 X) EX) 게시판, 공지사항
SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM, FIRST_NAME, SALARY FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC);

-- 공동순위를 구하는 방법 RANK(), DENSE_RANK()

-- RANK()
SELECT RANK() OVER(ORDER BY SALARY DESC) AS RANK,FIRST_NAME, SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC;
    
-- DENSE_RANK()
SELECT DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK,FIRST_NAME, SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC;
    
-- 중복순위 없애기
SELECT RANK() OVER(ORDER BY SALARY DESC, COMMISSION_PCT DESC, DEPARTMENT_ID DESC) AS RANK,
    DENSE_RANK() OVER(ORDER BY SALARY DESC, COMMISSION_PCT DESC, DEPARTMENT_ID DESC) AS DENSE_RANK,FIRST_NAME, SALARY, COMMISSION_PCT, DEPARTMENT_ID
    FROM EMPLOYEES
    ORDER BY SALARY DESC;
    
-- 부서별 순위 구하기
SELECT DEPARTMENT_ID, RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC, COMMISSION_PCT DESC, DEPARTMENT_ID DESC) AS RANK,
    DENSE_RANK() OVER(ORDER BY SALARY DESC, COMMISSION_PCT DESC, DEPARTMENT_ID DESC) AS DENSE_RANK,FIRST_NAME, SALARY, COMMISSION_PCT, DEPARTMENT_ID
    FROM EMPLOYEES
    ORDER BY SALARY DESC;