CREATE table USER (
    ID VARCHAR2(12) NOT NULL,
    PASS VARCHAR2(12) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    PHONE1 VARCHAR2(3) NOT NULL,
    PHONE2 VARCHAR2(4) NOT NULL,
    PHONE3 VARCHAR2(4) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    ZIPCODE VARCHAR2(7) NOT NULL,
    ADDRESS1 VARCHAR2(120) NOT NULL,
    ADDRESS2 VARCHAR2(50) NOT NULL
);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_ID_PK PRIMARY KEY(ID);