CREATE TABLE SUBJECT(
NO NUMBER NOT NULL,
S_NUM NUMBER(2) NOT NULL,
S_NAME VARCHAR2 NOT NULL,
CONSTRAINT SUBJECT_NO_UK UNIQUE(NO)
);

CREATE TABLE STUDENT(
NO NUMBER NOT NULL,
SD_NUM NUMBER(8) NOT NULL,
SD_NAME VARCHAR2 NOT NULL,
SD_ID VARCHAR2 NOT NULL,
SD_PASSWD VARCHAR2 NOT NULL,
S_NUM NUMBER(2) NOT NULL,
SD_JUMIN CHAR(14) NOT NULL,
SD_PHONE CHAR(13) NOT NULL,
SD_ADDRESS VARCHAR2 NOT NULL,
SD_EMAIL VARCHAR2 NOT NULL,
SD_DATE DATE NOT NULL DEFAULT(SYSDATE),
CONSTRAINT STUDENT_NO_UK UNIQUE(NO)
);

CREATE TABLE LESSON(
NO NOT NULL,
I_NUM CHAR(2) NOT NULL,
I_NAME VARCHAR2 NOT NULL,
CONSTRAINT LESSON_NO_UK UNIQUE(NO)
);

CREATE TABLE TRAINEE(
NO NUMBER NOT NULL,
SD_NUM NUMBER(8) NOT NULL,
I_NUM CHAR(2) NOT NULL,
T_SECTION VARCHAR2 NOT NULL,
T_DATE DATE NOT NULL DEFAULT(SYSDATE),
CONSTRAINT TRAINEE_NO_UK UNIQUE(NO)
);